-- MySQL Script generated by MySQL Workbench
-- Sun May 24 21:52:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema houserenting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema houserenting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `houserenting` DEFAULT CHARACTER SET utf8 ;
USE `houserenting` ;

-- -----------------------------------------------------
-- Table `houserenting`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houserenting`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Mobile_No` INT(15) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Street_Name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(25) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  `Postal_Code` INT(6) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houserenting`.`rent_house_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houserenting`.`rent_house_type` (
  `idrent_house_type` INT(11) NOT NULL AUTO_INCREMENT,
  `House_Type` ENUM('Townhouses', 'Duplexes', 'Quadplexes', 'Condominiums') NOT NULL,
  `SrcImg` VARCHAR(45) NOT NULL,
  `BedRooms` INT(11) NOT NULL,
  `BathRooms` INT(11) NOT NULL,
  `House_Title` VARCHAR(45) NOT NULL,
  `Square_Area` INT(11) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Price` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idrent_house_type`, `iduser`),
  INDEX `fkuser_idx` (`iduser` ASC) ,
  CONSTRAINT `fkuser`
    FOREIGN KEY (`iduser`)
    REFERENCES `houserenting`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houserenting`.`rent_house_type_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houserenting`.`rent_house_type_address` (
  `idrent_house_type` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `Area` VARCHAR(30) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street_Name` VARCHAR(45) NOT NULL,
  `Postal_Code` VARCHAR(45) NOT NULL,
  `Thana` VARCHAR(45) NOT NULL,
  `Road_No` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrent_house_type`, `iduser`),
  CONSTRAINT `fkrent_house_type1`
    FOREIGN KEY (`idrent_house_type` , `iduser`)
    REFERENCES `houserenting`.`rent_house_type` (`idrent_house_type` , `iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houserenting`.`find_house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houserenting`.`find_house` (
  `House_Type` VARCHAR(45) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street_Name` VARCHAR(45) NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `BedRooms` INT(11) NOT NULL,
  `BathRooms` INT(11) NOT NULL,
  `idrent_house_type` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idrent_house_type`, `iduser`),
  CONSTRAINT `fkrent_house_type_address1`
    FOREIGN KEY (`idrent_house_type` , `iduser`)
    REFERENCES `houserenting`.`rent_house_type_address` (`idrent_house_type` , `iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houserenting`.`find_house_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houserenting`.`find_house_has_user` (
  `idrent_house_type` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  `iduser1` INT(11) NOT NULL,
  PRIMARY KEY (`idrent_house_type`, `iduser`, `iduser1`),
  INDEX `fkuser1_idx` (`iduser1` ASC) ,
  INDEX `fkfind_house1_idx` (`idrent_house_type` ASC, `iduser` ASC) ,
  CONSTRAINT `fkfind_house1`
    FOREIGN KEY (`idrent_house_type` , `iduser`)
    REFERENCES `houserenting`.`find_house` (`idrent_house_type` , `iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkuser1`
    FOREIGN KEY (`iduser1`)
    REFERENCES `houserenting`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
